name: Release TBB binaries

on:
  release:
    types: [created, edited]

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # build and publish in parallel: linux/amd64
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
        exclude:
          - goarch: arm64
            goos: windows
    steps:
      - uses: actions/checkout@v2
      - uses: wangyoucao577/go-release-action@v1.24
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          project_path: "./"
          binary_name: "privado"
          goversion: "https://dl.google.com/go/go1.17.6.linux-amd64.tar.gz"
          extra_files: README.md
          asset_name: privado-${{ matrix.goos }}-${{ matrix.goarch }}
          overwrite: true
